# General
cache_dir: null
seed: 0
push_to_hub: false
hub_token: null
hub_model_id: null
# Model
conditioning_maps: [depth, normal, diffuse, shading, mask]
feed_empty_prompt: true
scale_destination_composite_to_minus_one_to_one: true
use_predictors_instead_of_gt: false
# Load model
noise_scheduler_name: ddim
pretrained_model_name_or_path: .cache/huggingface/hub/models--stabilityai--stable-diffusion-2-1/snapshots/5cae40e6a2745ae2b01ad92ae5043f95f23644d6
# pretrained_model_name_or_path: stabilityai/stable-diffusion-2-1
controlnet_model_name_or_path: null
revision: null
tokenizer_name: null
vae_type: normal
# Performance
gradient_accumulation_steps: 1
gradient_checkpointing: false
mixed_precision: null
allow_tf32: false
enable_xformers_memory_efficient_attention: true
set_grads_to_none: true
dynamo_backend: null
# dynamo_backend: INDUCTOR
# Dataset
dataset_name: openrooms_mainxml1
dataset_dir: ../datasets/openrooms_mainxml1
dataset_config_name: null
image_column: image
conditioning_image_column: conditioning_image
caption_column: text
max_train_samples: null
proportion_empty_prompts: 0
resolution: 512
train_batch_size: 4
val_batch_size: 4
aug:
  fill_value: -1
val_scheduler:
  name: ddim
  kwargs:
    timestep_spacing: 'trailing'
    rescale_betas_zero_snr: true
# Tracker
tracker_project_name: controlnet
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: False

eval:
  device: cuda
  weight_dtype: fp16
  num_inference_steps: 20
  eval_batch_size: 1
  controlnet_model_name_or_path: outputs_cloud/openrooms_ddim_wo_bg/checkpoints-808000
  results_dir: results_v2/${now:%Y-%m-%d_%H-%M-%S}
  # predictor_names: [depthanything, precompute_stablenormal, precompute]
  # predictor_names: [metric3d, precompute_stablenormal, precompute]
  # predictor_names: [depthanythingv2_relative, omnidata, precompute]
  # predictor_names: [depthanythingv2_relative, metric3d, precompute]
  # predictor_names: [depthanythingv2_relative, precompute_stablenormal, dfnet]
  # predictor_names: [depthanythingv2_relative, precompute_stablenormal, precompute]
  predictor_names: [zoedepth, precompute_stablenormal, precompute]
  # predictor_names: [zoedepth, stablenormal, precompute]
  use_rgb_as_diffuse: false
  albedo_gamma_correction: false
  depth_scale_factor: 1
  adjust_bgdepth_to_objdepth: false
  obj_color_balance: true
  # shading_maskout_mode: None
  # shading_maskout_mode: BBox
  # shading_maskout_mode: BBoxWithDepth
  shading_maskout_mode: PointCloud
  # shading_maskout_mode: Cone
  shading_maskout_bbox_dilation: 30
  shading_maskout_bbox_depth_range: 4.0
  point_cloud_fov: 50
  shading_maskout_pc_range: 0.8
  shading_maskout_pc_type: relative
  shading_maskout_pc_range_relative: 1.0
  shading_maskout_cone_radius: 0.6
  shading_maskout_obj_dilation: 0
  # shading_maskout_pc_above_cropping_type: abovebbox
  shading_maskout_pc_above_cropping_type: argmin
  shading_maskout_cone_angle: 90
  post_compositing: true
  output_all: false