defaults:
  - sdi_default
  - _self_

resolution: 512
train_batch_size: 1
dataloader_num_workers: 2

dataset_name: labo
dataset_dir: ../labo/GT_emission_envmap
pretrained_model_name_or_path: .cache/huggingface/hub/models--stabilityai--stable-diffusion-2-1/snapshots/5cae40e6a2745ae2b01ad92ae5043f95f23644d6

enable_xformers_memory_efficient_attention: false
vae_type: normal
vae_name_or_path: .cache/huggingface/hub/models--cross-attention--asymmetric-autoencoder-kl-x-1-5/snapshots/8a721838bf5546eb21c954b66f37f531632b5737

# conditioning_maps: [depth, normal, diffuse, shading, mask]
conditioning_maps: [normal, diffuse, shading, mask]
seed: 469

eval:
  device: cuda
  weight_dtype: fp16
  num_inference_steps: 20
  eval_batch_size: 1
  # controlnet_model_name_or_path: checkpoints/openrooms_7days
  controlnet_model_name_or_path: checkpoints/openrooms_2days_wo_depth
  # controlnet_model_name_or_path: checkpoints/interior_verse_2days
  # controlnet_model_name_or_path: checkpoints/interior_verse_7days
  results_dir: results_v2/${now:%Y-%m-%d_%H-%M-%S}
  # predictor_names: [depthanything, precompute_stablenormal, precompute]
  # predictor_names: [metric3d, precompute_stablenormal, precompute]
  # predictor_names: [depthanythingv2_relative, omnidata, precompute]
  # predictor_names: [depthanythingv2_relative, metric3d, precompute]
  # predictor_names: [depthanythingv2_relative, precompute_stablenormal, dfnet]
  # predictor_names: [depthanythingv2_relative, precompute_stablenormal, precompute]
  # predictor_names: [zoedepth, stablenormal, precompute]
  predictor_names: [zoedepth, precompute_stablenormal, precompute]
  # predictor_names: [zoedepth, stablenormal, precompute]
  # predictor_names: [zoedepth, omnidata, precompute]
  use_rgb_as_diffuse: false
  depth_scale_factor: 1
  adjust_bgdepth_to_objdepth: false
  obj_color_balance: true
  # shading_maskout_mode: None
  shading_maskout_mode: BBox
  # shading_maskout_mode: BBoxWithDepth
  # shading_maskout_mode: PointCloud
  shading_maskout_bbox_dilation: 50
  shading_maskout_bbox_depth_range: 4.0
  point_cloud_fov: 50
  shading_maskout_pc_range: 0.8
  shading_maskout_pc_type: relative
  shading_maskout_pc_range_relative: 1.0
  shading_maskout_cone_radius: 0.6
  shading_maskout_obj_dilation: 0
  # shading_maskout_pc_above_cropping_type: abovebbox
  shading_maskout_pc_above_cropping_type: argmin
  shading_maskout_cone_angle: 90
  post_compositing: true
  output_all: false